version: "3.9"

services:
  db:
    image: "postgres:16.1-alpine"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "green_thunder"

  server:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/green_thunder?schema=public"
    depends_on:
      - db